### ISSUE TITLE
IR reader hardware suggestion

### ISSUE THREAD

**Issue by entorb** [christian-heusel/esp32-smartMeter#1]
Moin Christian,
thank you very much for sharing your code!

I want to achieve something quite similar: read an Iskra MT681 and display the data in Grafana. 

Can you please suggest IR reader hardware for me?

My Iskra MT681 has already been unlocked via the code, so I think a read-only solutions should be sufficient. 

On the [volkszaehler-site](https://wiki.volkszaehler.org/hardware/controllers/ir-schreib-lesekopf) you linked, there are many variants and I am uncertain which would be best.
I was considering a TCRT5000 based element, like
https://www.az-delivery.de/products/linienfolger-modul
or even just a OSRAM SFH 309 FA diode and resistor, as described at
https://wiki.volkszaehler.org/hardware/controllers/ir-schreib-lesekopf-pi-ausgang

What would you recommend?

**Comment by christian-heusel** [comment]
Hey @entorb! 🤗

We (@Heusel & me) have basically bought something for this online, see i.e [this ebay item](https://www.ebay.de/itm/314015465828). I theory also simpler setups should work, but its a great prebuilt package since it gives you the casing and mount (via magnet) with it.

We even tried to build something, but as we finished our Proof of Concept the above sensor had already arrived.

In general, we're interested in how the codebase works out for you and hope its useful 😄

**Comment by entorb** [comment]
Thank you so much, will try that one and your code base

**Comment by christian-heusel** [comment]
I guess we can also consider this request completed 😊  If you have any similar question just re-open this thread or file a new issue 🤗
